all: bst.out ht.out list.out sq.out

bst.out:
	g++ -o bst.out -I .. testbst.cpp

ht.out:
	g++ -o ht.out -I .. testht.cpp

list.out:
	g++ -o list.out -I .. testlist.cpp

sq.out:
	g++ -o sq.out -I .. testsq.cpp

clean:
	rm -rf *.out *.stackdump *~
